### ISSUE TITLE
設定項目がユーザーにとっては分かりづらい？

### ISSUE THREAD

**Issue by KazinaG** [KazinaG/Smart-Bookmark-Sorter#25]

**Comment by KazinaG** [comment]
説明をOption.htmlに書くのはどうですか？
defaultの設定で基本的に問題ないように作られてはあるので、わからない人は触らないのでokな気がします。
@ikari-s 見る人向けに一旦は言葉で説明すればいい気がしますがどうでしょう。

**Comment by ikari-s** [comment]
見る人向けの説明は具体的な例とかも必要な気がします。

**Comment by KazinaG** [comment]
最初に見せたグラフを動的（実際の設定を反映）に表示させればうまく説明できそうです。

**Comment by KazinaG** [comment]
#81 にもある、弱・中・強の方式でプルダウンを一つにして、Sort Level、High, Middle, Low, Noneにする。
Noneの場合はソートしないようにする。
順番をSort Target, Sort Order, Sort Levelにする。
Sort Targetは、未選択でない場合は、しまっておく。

**Comment by KazinaG** [comment]
7b8c549のコミットでは、「Sort LevelをHigh, Middle, Low, Noneにする」に対応。
「Noneの場合はソートしないようにする」には非対応。
